version: '3'
services:
  artwork_db:
    build: docker/artwork_db
    image: artwork_db
    container_name: artwork_db
    restart: always
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --sql-mode=NO_ENGINE_SUBSTITUTION
      - --character-set-server=utf8 
      - --collation-server=utf8_unicode_ci
    volumes: 
      - artwork_db_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}

  artwork_server:
    build: docker/artwork_server
    image: artwork_server
    container_name: artwork_server
    restart: always
    ports:
      - ${PORT}:80
    volumes: 
      - ./src:/var/www/html
    hostname: artwork.local
    environment:
      MYSQL_HOST: artwork_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      EDITMODE_HASH: ${EDITMODE_HASH}
      TZ: ${TZ}

  artwork_export:
    build: docker/artwork_export
    image: artwork_export
    container_name: artwork_export
    restart: always
    volumes: 
      - ./src:/var/www/html
      - ./docker/artwork_export/crontab:/var/spool/cron/crontabs/root
    environment:
      MYSQL_HOST: artwork_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      EDITMODE_HASH: ${EDITMODE_HASH}
      TZ: ${TZ}
      LANG: C.UTF-8

volumes:
  artwork_db_volume:
    driver: local
